<?php

$photoData = array(
    array(
        "id" => "1",
        "sourceId" => "5590273098322362706",
        "albumId" => "2",
        "filename" => "IMG_0360.JPG",
        "description" => "Kai is not so sure about his new friend",
        "linkUrl" => "https://picasaweb.google.com/michaeltoppa/2011Honolulu",
        "contentUrl" => "https://lh5.googleusercontent.com/_e1IlgcNcTSg/TZSjw67tQVI/AAAAAAAAIik/LI3EeUEGJYs/IMG_0360.JPG",
        "contentType" => "image/jpeg",
        "width" => "1024",
        "height" => "768",
        "takenTimestamp" => "1301524665",
        "uploadedTimestamp" => "1301586883",
        "tags" => "",
        "lastSync" => "1304249789",
        "includeInRandom" => "Y",
        "sourceOrder" => "1",
        "fstop" => "3.2",
        "make" => "Canon",
        "model" => "Canon PowerShot SD78",
        "exposure" => "0.0125",
        "focalLength" => "5.9",
        "iso" => "100",
        "albumType" => "picasa"
    ),
    array(
        "id" => "1",
        "sourceId" => "5106043336352724898",
        "albumId" => "1",
        "filename" => "clinton.jpg",
        "description" => "Maria's friend Edward requested one of these from the White House for us (they'll give them to anyone)",
        "linkUrl" => "https://picasaweb.google.com/100291303544453276374/1999MikeAndMariaSWedding#5106043336352724898",
        "contentUrl" => "http://lh6.ggpht.com/-Leq__IInkho/RtxPXIcN96I/AAAAAAAAIg8/VDM5XTFaRjs/clinton.jpg",
        "contentType" => "image/jpeg",
        "width" => "640",
        "height" => "405",
        "takenTimestamp" => "0",
        "uploadedTimestamp" => "1188843356",
        "tags" => "",
        "lastSync" => "1313368709",
        "includeInRandom" => "Y",
        "sourceOrder" => "1",
        "fstop" => "",
        "make" => "",
        "model" => "",
        "exposure" => "",
        "focalLength" => "",
        "iso" => "",
        "albumType" => "picasa"
    )
);